version: "3.5"

services:
#     app:
#         # service name
#         build: . # build from Dockerfile
#         volumes:
#           - "./:/usr/src/app"
#           #- /usr/src/app/node_modules # Remove this if you have pure JS dependencies
#         command: sh -c "[ ! -f .env.local ] && cp .env.example .env.local; npm install; npx sequelize-cli db:migrate; npx sequelize-cli db:seed:all && npm run dev"
#         ports:
#             - 3000:3000
    db:
        container_name: postgres-db-server
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: boilerplate
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080

    # elasticsearch:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    #     container_name: elasticsearch
    #     environment:
    #         - discovery.type=single-node
    #         - ES_JAVA_OPTS=-Xms512m -Xmx512m
    #     ulimits:
    #         memlock:
    #             soft: -1
    #             hard: -1
    #     volumes:
    #         - es_data:/usr/share/elasticsearch/data
    #     ports:
    #         - 9200:9200
    #         - 9300:9300
    # kibana:
    #     image: docker.elastic.co/kibana/kibana:7.10.0
    #     environment:
    #         ELASTICSEARCH_URL: http://elasticsearch:9200
    #     ports:
    #         - "5601:5601"

volumes:
    db_data:
    es_data: